# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Job1
  steps:
  - script: echo Job1 - Hello, world, changed for test!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
- job: Job2
  dependsOn: Job1
  steps:
  - script: echo Job2!
    displayName: 'Run a one-line script'
- job: Job3
  steps:
  dependsOn: Job1
  - script: echo Job3!
    displayName: 'Run a one-line script'
- job: Job4
  steps:
  dependsOn:
  - Job2
  - Job3
  - script: echo Job4!
    displayName: 'Run one-line after other jobs completion'
